# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = ["pre-commit"]
minimum_prek_version = "0.3.4"
default_install_hook_types = ["pre-push"]

[[repos]]
repo = "builtin"
hooks = [
    { id = "trailing-whitespace", priority = 0 },
    { id = "end-of-file-fixer", priority = 0 },
    { id = "check-added-large-files", args = ["--maxkb=1024"], priority = 0 },
    { id = "check-case-conflict", priority = 0 },
    { id = "check-merge-conflict", priority = 0 },
    { id = "check-toml", priority = 0 },
    { id = "check-json", priority = 0 },
    { id = "check-yaml", priority = 0 },
    { id = "check-symlinks", priority = 0 },
    { id = "mixed-line-ending", args = ["--fix=lf"], priority = 0 },
    { id = "detect-private-key", priority = 0 },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.44.0"  # prek autoupdate will fill this
hooks = [{ id = "typos", priority = 1 }]

[[repos]]
repo = "https://github.com/igorshubovych/markdownlint-cli"
rev = "v0.48.0"
hooks = [{ id = "markdownlint", priority = 1, stages = ["pre-commit"], types_or = ["markdown"] }]

[[repos]]
repo = "https://github.com/lycheeverse/lychee"
rev = "lychee-v0.23.0"  # lychee tags nightly as latest; prek autoupdate may switch to it
hooks = [{ id = "lychee", args = ["--no-progress"], priority = 1, stages = ["pre-push"], types_or = ["markdown"] }]
